-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")

vim.keymap.set("n", "<leader>hr", function()
  local raylib_template = {
    '#include "raylib.h"',
    "",
    "//------------------------------------------------------------------------------------",
    "// Program main entry point",
    "//------------------------------------------------------------------------------------",
    "int main(void)",
    "{",
    "    // Initialization",
    "    //--------------------------------------------------------------------------------------",
    "    const int screenWidth = 800;",
    "    const int screenHeight = 450;",
    "",
    '    InitWindow(screenWidth, screenHeight, "raylib [core] example - basic window");',
    "",
    "    SetTargetFPS(60);               // Set our game to run at 60 frames-per-second",
    "    //--------------------------------------------------------------------------------------",
    "",
    "    // Main game loop",
    "    while (!WindowShouldClose())    // Detect window close button or ESC key",
    "    {",
    "        // Update",
    "        //----------------------------------------------------------------------------------",
    "        // TODO: Update your variables here",
    "        //----------------------------------------------------------------------------------",
    "",
    "        // Draw",
    "        //----------------------------------------------------------------------------------",
    "        BeginDrawing();",
    "            ClearBackground(RAYWHITE);",
    '            DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);',
    "        EndDrawing();",
    "        //----------------------------------------------------------------------------------",
    "    }",
    "",
    "    // De-Initialization",
    "    //--------------------------------------------------------------------------------------",
    "    CloseWindow();        // Close window and OpenGL context",
    "    //--------------------------------------------------------------------------------------",
    "",
    "    return 0;",
    "}",
  }

  vim.api.nvim_put(raylib_template, "l", true, true)
end, { desc = "Insert full Raylib Hello World in C" })

vim.keymap.set("n", "<leader>cr", function()
  local raylib_cmake_template = {
    "# Compiler",
    "CC = gcc",
    "",
    "# Compiler flags",
    "CFLAGS = -Wall -Wextra -std=c99",
    "",
    "# Libraries",
    "LDFLAGS = -lraylib -lGL -lm -lpthread -ldl -lrt -lX11",
    "",
    "# Source files",
    "SRCS = main.c",
    "",
    "# Object files",
    "OBJS = $(SRCS:.c=.o)",
    "",
    "# Executable name",
    "TARGET = main",
    "",
    "# Default rule",
    "all: $(TARGET)",
    "",
    "# Link the executable",
    "$(TARGET): $(OBJS)",
    "\t$(CC) $(OBJS) -o $(TARGET) $(LDFLAGS)",
    "",
    "# Compile source files into object files",
    "%.o: %.c",
    "\t$(CC) $(CFLAGS) -c $< -o $@",
    "",
    "# Clean rule",
    "clean:",
    "\trm -f $(OBJS) $(TARGET)",
  }
  vim.api.nvim_put(raylib_cmake_template, "l", true, true)
end, { desc = "Insert full Raylib makefile" })
